App2/src/objects/Carriage__c.object
<CustomObject>
    <label>Carriage</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App2/src/objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App2/src/objects/Passenger__c.object
<CustomObject>
    
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NIP__c</fullName>
        <label>NIP</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PIN__c</fullName>
        <label>PIN</label>
        <precision>11</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App2/src/objects/Seat__c.object
<CustomObject>
    <fields>
        <fullName>Carriage__c</fullName>
        <label>Carriage</label>
        <referenceTo>Carriage__c</referenceTo>
        <relationshipLabel>Seats</relationshipLabel>
        <relationshipName>Seats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Window</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Corridor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Table</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Seat</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

App2/src/objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIckets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

App2/src/classes/TicketCtrl.cls
public class TicketCtrl {
    public String firstName { get; public set; }
	public String lastName { get; public set; }
	public Integer pin { get; public set; }
	public String email { get; public set; }
	public Boolean isInvoiceNeed { get; public set; }
	public String businessName { public get; public set; }
	public Integer nip { get; public set; }
	public String postalCode { get; public set; }
	public String city { get; public set; }
	public String street { get; public set; }
	public Integer ticketsNumber { get; public set; }
	public Ticket__c ticket { get; public set; }
	public Carriage__c carriage { get; public set; }
	public Boolean isTable { get; public set; }
	String defaultSitOption = 'okno';
		
	public TicketCtrl() {
		ticket = new Ticket__c();
		carriage = new Carriage__c();
		
	}
	
	public String getDefaultSitOption() {
        return defaultSitOption;
    }
                    
    public void setDefaultSitOption(String defaultSitOption) { this.defaultSitOption = defaultSitOption; }
	
	public List<SelectOption> getSpots() {
		List<SelectOption> options = new List<SelectOption>();
		options.add(new Selectoption('okno', 'WINDOW SIDE'));
		options.add(new Selectoption( 'korytarz', 'PASSAGE SIDE'));
		options.add(new Selectoption('stojace', 'STANDING'));
	return options;
	}
	
    public void addTicket() {
    	ticket = new Ticket__c();
    	ticket.name= 'ticket';
    	ticket.Discount__c = getDefaultSitOption();
		
    	Passenger__c passenger = new Passenger__c();
    	passenger.City__c = 'HardCoded';
    	passenger.Company_Name__c = businessName;
    	passenger.Email__c = email;
    	passenger.Name = firstName;
    	passenger.Last_Name__c = lastName;
    	passenger.NIP__c =  nip;
    	passenger.PIN__c = pin;
    	passenger.Postal_Code__c = postalCode;
    	passenger.Street__c = street;
    	
    	Seat__c seat = new Seat__C();
    	//seat.Location__c = getDefaultSitOptions();
    	
    	try {
    		insert passenger;
    		insert ticket;
    	} catch(DmlException e) {
    		system.debug(e.getMessage());
    	}
    }
    
    public PageReference moveToSearchStationPage() {
    	return null;
    }
    
    public PageReference buyTicket() {
    	return null;
    }
}