App2/src/objects/Carriage__c.object
<CustomObject>
    <fields>
        <fullName>Bicycles_Transport__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bicycles Transport</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Carriage_With_Tables__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Carriage With Tables</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Second</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buffet Car</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Disabled_People_Support__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disabled People Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Seats__c</fullName>
        <label>Number Of Seats</label>
        <picklist>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>64</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Carriage</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App2/src/objects/Carriage_on_Train__c.object
<CustomObject>

    <fields>
        <fullName>Carriage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carriage</label>
        <referenceTo>Carriage__c</referenceTo>
        <relationshipLabel>Carriages on Trains</relationshipLabel>
        <relationshipName>Carriages_on_Trains</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Train__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Train</label>
        <referenceTo>Train__c</referenceTo>
        <relationshipLabel>Carriages on Trains</relationshipLabel>
        <relationshipName>Carriages_on_Trains</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Carriage on Train</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carriages on Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App2/src/objects/Train__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regio</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>InterCity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Train</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App2/src/classes/TrainCarriagesCtrl.cls
public class TrainCarriagesCtrl {
	public Id trainId {get;set;}
	public Id carriageId {get;set;}
	public List<Carriage__c> addedCarriages {get;set;}
	
	public TrainCarriagesCtrl() {
		addedCarriages = new List<Carriage__c> ();
	}
	
	public List<Train__c> getTrains() {
		List<Train__c> trains = new List<Train__c> ();
		trains = [SELECT Id, Name, Type__c FROM Train__c];	
		return trains;
	}
	
	public List<Carriage__c> getCarriages() {
		List<Carriage__c> carriages = new List<Carriage__c> ();
		carriages = [SELECT Id, Name, Number_Of_Seats__c, Bicycles_Transport__c, Class__c, 
			Carriage_With_Tables__c, Disabled_People_Support__c FROM Carriage__c];	
		return carriages;
	}
	
	public Carriage__c getCarriageById(Id crId) {
		Carriage__c carriages = new Carriage__c ();
		carriages = [SELECT Id, Name, Number_Of_Seats__c, Bicycles_Transport__c, Class__c, 
			Carriage_With_Tables__c, Disabled_People_Support__c FROM Carriage__c WHERE Id = :crId];	
		return carriages;
	}
	
	public List<SelectOption> getTrainOptions() {
		List<SelectOption> trainOptions = new List<SelectOption> ();
		for (Train__c tr : getTrains()) {
			trainOptions.add(new SelectOption(tr.Id, tr.Name));
		}
		return trainOptions;
	}
	
	public List<SelectOption> getCarriageOptions() {
		List<SelectOption> carriageOptions = new List<SelectOption> ();
		for (Carriage__c cr : getCarriages()) {
			carriageOptions.add(new SelectOption(cr.Id, cr.Name + '; class:'+cr.Class__c + '; seats:' + cr.Number_Of_Seats__c ));
		}
		return carriageOptions;
	}
	
	public PageReference addCarriageToList() {
		
		Carriage__c c = new Carriage__c();
		c = getCarriageById(carriageId);
		addedCarriages.add(c);
		return null;
	}
	
	public PageReference saveCarriagesOfTrain() {
		List<Carriage_on_Train__c> carriagesOnTrainJunction = new List<Carriage_on_Train__c> ();
		for (Carriage__c cr : addedCarriages) {
			Carriage_on_Train__c carriageOnTrain = new Carriage_on_Train__c();
			carriageOnTrain.Train__c = trainId;
			carriageOnTrain.Carriage__c = cr.Id;
			carriagesOnTrainJunction.add(carriageOnTrain);
		}
		insert carriagesOnTrainJunction; 		
		return null;
	}
}