App1 project/sk/src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Serial__c</fullName>
        <label>Serial</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

App1 project/sk/src/classes/AddNewCarRecord.cls
public class AddNewCarRecord {
	public Car__c car{get; set;}
    public String carName{get; set;}
    public Integer weight{get; set;}
    public String serial{get; set;}
	
	public AddNewCarRecord() {
	}
	
	
	public PageReference addCarRecord() {
		if(fieldsNotEmpty()){
			insertRecord();
			return moveToList();
	    } else {
	    	showErrorInfo();
	    	return null;
	    }
    }
    
    private void insertRecord() {
    try {
    	Car__c  newCar = new Car__c(Name=carName, serial__c=serial, weight__c=weight);
    	insert newCar;
	    } catch(DmlException e) {
	    	ApexPages.addMessages(e);
	    	system.debug(e.getMessage());
	    }
    }
    
    private Boolean fieldsNotEmpty() {
	    if(carName.length() > 0){
	    	return true;
	    } else { 
	    	//car.name.addError('Error');
	    return false;
	    }
	    
	    if(serial.length() > 0){
	    	return true;
	    } else {
	    return false;
	    }
    }
    
    public pageReference moveToList() {
    	PageReference listPage = Page.Cars;//('/apex/Cars');
		    //listPage.setRedirect(true);
    return listPage;
    }
    
    public void showErrorInfo() {
	    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Field cant by empty!');
	    ApexPages.addMessage(myMsg);
    }
    
}